daemon:
    name: Developer Cluster

general:
    eventlogger: 127.0.0.1:8190
    dc_files:
        - ../dclass/otp.dc
        - ../dclass/pirates.dc

messagedirector:
    bind: 127.0.0.1:7100

uberdogs:
    - class: CentralLogger
      id: 4688
      anonymous: false

    - class: ClientServicesManager
      id: 4665
      anonymous: true

    - class: ChatAgent
      id: 4681
      anonymous: false

    - class: FriendManager
      id: 4501
      anonymous: false

    - class: AvatarFriendsManager
      id: 4686
      anonymous: false

    - class: PiratesFriendsManager
      id: 4680
      anonymous: false

    - class: DistributedMatchMaker
      id: 4700
      anonymous: false

    - class: DistributedGuildManager
      id: 4701
      anonymous: false

    - class: DistributedTravelAgent
      id: 4679
      anonymous: false

    - class: DistributedCrewMatchManager
      id: 4690
      anonymous: false

roles:
    - type: clientagent
      bind: 0.0.0.0:7969
      version: "pirates-dev"
      tls:
        certificate: ../certs/dev/pserver.crt
        key_file: ../certs/dev/pserver.key
        cert_authority: ../certs/dev/pclient.crt
      client:
          relocate: true
          add_interest: enabled
      channels:
          min: 1000000000
          max: 1000001000

    - type: stateserver
      control: 4002

    - type: database
      control: 4003
      generate:
          min: 100000000
          max: 399999999
      backend:
        type: mongodb
        server: mongodb://127.0.0.1:27017/porgame

    - type: dbss
      database: 4003
      ranges:
          - min: 100000000
          - max: 399999999

    - type: eventlogger
      bind: 127.0.0.1:8190
      output: ../logs/events-%y%m%d_%H%M%S.log
